"""
Google Gemini-powered AI Advisor for the Digital Twin Greenhouse.

This is the real AI brain — every response is generated by Google Gemini
with full context from live sensor data, historical trends, actuator states,
alerts, and crop profiles. All analytical endpoints flow through this service.
"""

import json
import io
import base64
import time
import traceback
from datetime import datetime
from typing import List, Dict, Optional, Tuple
from collections import deque

import numpy as np

CACHE_TTL_SECONDS = 90

FALLBACK_MODELS = [
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite",
]

from backend.config import settings
from backend.database import tsdb
from backend.models import get_now
from backend.services.twin_state import twin_state
from backend.services.ai_advisor import (
    advisor as rule_advisor,
    calculate_vpd,
    calculate_dew_point,
    CROP_PROFILES,
)
from backend.services.weather_service import weather_service

SYSTEM_PROMPT = """You are GreenMind, an expert AI agronomist and digital twin advisor for a small-scale greenhouse and water-culture (hydroponic) farm. You are embedded inside a real-time digital twin system that gives you live sensor data from the greenhouse.

## Your Personality
- Friendly, professional, and encouraging to farmers of all skill levels
- Use plain language but back up advice with specific numbers from the sensor data
- When something is wrong, be direct about it and give a clear action plan
- Use markdown formatting: **bold** for emphasis, bullet points for lists, numbered lists for steps
- Keep answers concise but thorough (2-4 paragraphs typical, more for reports)

## Your Capabilities
1. **Real-time Monitoring**: You see ALL live sensor data from the greenhouse
2. **Crop Expertise**: You know optimal conditions for many greenhouse crops
3. **VPD Analysis**: You can calculate and explain Vapor Pressure Deficit
4. **Trend Analysis**: You can interpret sensor trends (rising, falling, stable)
5. **Actuator Awareness**: You know which equipment is on/off
6. **Alert Context**: You know about any active warnings
7. **Hydroponics Expertise**: pH, EC, nutrient management, root zone health
8. **Disease Prevention**: Environmental conditions that promote or prevent disease
9. **Energy Efficiency**: Identify wasteful actuator configurations

## Agentic AI Capabilities
You are also an **Agentic AI** — you can directly control greenhouse actuators:
- **Water Pump A** (pump_a) — irrigates Bed A / Substrate A
- **Water Pump B** (pump_b) — irrigates Bed B / Substrate B
- **Water Pump C** (pump_c) — irrigates Bed C / Substrate C

When users give natural language commands (e.g. "帮我浇水", "turn on pump A", "give Bed B some water"):
- Identify which actuator(s) to control
- State what you will do BEFORE doing it
- After execution, report the result clearly
- If the action is risky or involves multiple actuators, ask for confirmation first

When responding to **"Hello Twin"** greetings:
- Proactively analyze ALL current sensor data
- Give a brief health summary with actual numbers
- Highlight any warnings or anomalies
- Suggest helpful actions the user might want

## Important Rules
- ALWAYS reference actual sensor values from the data provided — never guess
- If a value looks dangerous, say so clearly with urgency
- Suggest specific actuator actions (e.g., "Turn on the exhaust fan") when relevant
- Calculate VPD when temperature and humidity are available (SVP = 0.6108 × e^(17.27T/(T+237.3)), VPD = SVP - AVP)
- When you don't know something, say so honestly
- For what-if scenarios, reason through the physical effects step by step
"""


def _build_sensor_context() -> str:
    """Build a rich text snapshot of all current greenhouse data for Gemini."""
    latest = tsdb.get_all_latest()
    if not latest:
        return "No sensor data available yet. The system is still initializing."

    lines = ["## Current Greenhouse Sensor Data (Live)"]
    lines.append(f"Timestamp: {get_now().isoformat()}\n")

    zone_map = {}
    for key, reading in latest.items():
        zone_id = reading.zone_id
        if zone_id not in zone_map:
            zone_map[zone_id] = []
        zone_map[zone_id].append(reading)

    zone_labels = {
        "zone_air": "Greenhouse Condition",
        "zone_bed_a": "Substrate A",
        "zone_bed_b": "Substrate B",
        "zone_bed_c": "Substrate C",
    }

    for zone_id, readings in zone_map.items():
        lines.append(f"### {zone_labels.get(zone_id, zone_id)}")
        for r in readings:
            trend = _get_trend(zone_id, r.sensor_type.value)
            quality_flag = " [LOW QUALITY]" if r.quality < 0.5 else ""
            lines.append(f"- {r.sensor_type.value}: {r.value} {r.unit} (trend: {trend}){quality_flag}")
        lines.append("")

    # VPD calculation — prefer air temperature, fall back to avg soil temp
    air_temp_r = tsdb.get_latest("zone_air", "temperature")
    rh_r = tsdb.get_latest("zone_air", "humidity")
    if air_temp_r and rh_r:
        avg_temp = air_temp_r.value
        vpd = calculate_vpd(avg_temp, rh_r.value)
        dp = calculate_dew_point(avg_temp, rh_r.value)
        lines.append(f"### Derived Metrics")
        lines.append(f"- VPD: {vpd} kPa (air temp {avg_temp:.1f}°C)")
        lines.append(f"- Dew Point: {dp}°C")
        lines.append("")
    else:
        soil_temps = [
            tsdb.get_latest(f"zone_bed_{bed}", "soil_temperature")
            for bed in ("a", "b", "c")
        ]
        valid_temps = [r for r in soil_temps if r is not None]
        if valid_temps and rh_r:
            avg_temp = sum(r.value for r in valid_temps) / len(valid_temps)
            vpd = calculate_vpd(avg_temp, rh_r.value)
            dp = calculate_dew_point(avg_temp, rh_r.value)
            lines.append(f"### Derived Metrics")
            lines.append(f"- VPD: {vpd} kPa (using avg soil temp {avg_temp:.1f}°C as proxy)")
            lines.append(f"- Dew Point: {dp}°C")
            lines.append("")

    # Actuator states
    actuators = twin_state.get_all_actuators()
    if actuators:
        lines.append("### Actuator States")
        for a in actuators:
            lines.append(f"- {a.name} ({a.actuator_id}): {a.state.value}")
        lines.append("")

    # Active alerts
    alerts = twin_state.get_alerts()
    if alerts:
        lines.append(f"### Active Alerts ({len(alerts)})")
        for al in alerts[:10]:
            lines.append(f"- [{al.severity.value.upper()}] {al.message}")
        lines.append("")

    # Outdoor weather (Open-Meteo) — helps Gemini reason about indoor vs outdoor
    try:
        weather = weather_service.get_weather()
        cur = weather.get("current", {}) or {}
        nxt = weather.get("next_12h", {}) or {}
        if cur:
            lines.append("### Outdoor Weather (Live)")
            lines.append(f"- Condition: {cur.get('condition', 'n/a')}")
            if cur.get("temp_c") is not None:
                lines.append(f"- Outdoor temp: {cur['temp_c']}°C")
            if cur.get("humidity_pct") is not None:
                lines.append(f"- Outdoor humidity: {cur['humidity_pct']}%")
            if cur.get("cloud_cover_pct") is not None:
                lines.append(f"- Cloud cover: {cur['cloud_cover_pct']}%")
            if cur.get("wind_kmh") is not None:
                lines.append(f"- Wind: {cur['wind_kmh']} km/h")
            lines.append("")
        if nxt and nxt.get("max_temp_c") is not None:
            lines.append("### 12-Hour Weather Forecast")
            lines.append(f"- Temp range: {nxt.get('min_temp_c')}°C — {nxt.get('max_temp_c')}°C")
            lines.append(f"- Max rain probability: {nxt.get('max_rain_prob_pct', 0)}%")
            lines.append(f"- Total expected rain: {nxt.get('total_rain_mm', 0)} mm")
            lines.append("")
    except Exception as e:
        print(f"[GeminiAdvisor] Weather context error: {e}")

    # Active crop
    crop = rule_advisor.get_crop_profile()
    lines.append(f"### Active Crop Profile: {crop.name}")
    lines.append(f"- Ideal temp: {crop.temp_min}-{crop.temp_max}°C (best: {crop.temp_ideal}°C)")
    lines.append(f"- Ideal humidity: {crop.rh_min}-{crop.rh_max}%")
    lines.append(f"- Ideal pH: {crop.ph_min}-{crop.ph_max}")
    lines.append(f"- Ideal EC: {crop.ec_min}-{crop.ec_max} mS/cm")
    lines.append(f"- Ideal VPD: {crop.vpd_min}-{crop.vpd_max} kPa")
    lines.append(f"- Light: {crop.light_hours}h/day, DLI target: {crop.light_dli} mol/m²/day")
    lines.append(f"- Notes: {crop.notes}")

    return "\n".join(lines)


def _build_history_context(zone_id: str, sensor_type: str, count: int = 30) -> str:
    """Get recent history for a sensor as text."""
    history = tsdb.get_recent_values(zone_id, sensor_type, count=count)
    if not history:
        return "No historical data."
    values = [v for _, v in history]
    arr = np.array(values)
    return (
        f"Last {len(values)} readings — "
        f"min: {arr.min():.1f}, max: {arr.max():.1f}, "
        f"mean: {arr.mean():.1f}, std: {arr.std():.2f}, "
        f"latest: {values[-1]:.1f}"
    )


def _get_trend(zone_id: str, sensor_type: str) -> str:
    history = tsdb.get_recent_values(zone_id, sensor_type, count=20)
    if len(history) < 5:
        return "insufficient data"
    values = [v for _, v in history]
    slope = (values[-1] - values[0]) / len(values)
    if abs(slope) < 0.05:
        return "stable"
    return "rising" if slope > 0 else "falling"


class GeminiAdvisor:
    """Google Gemini-powered greenhouse AI advisor with automatic model fallback."""

    def __init__(self):
        self._client = None
        self._chat_sessions: Dict[str, object] = {}
        self._conversation_history: deque = deque(maxlen=50)
        self._initialized = False
        self._init_error = None
        self._cache: Dict[str, Tuple[float, dict]] = {}
        self._model_name = ""
        self._active_model = ""
        self._blocked_models: Dict[str, float] = {}
        self._rate_limit_until = 0.0
        self._initialize()

    def _get_cached(self, key: str) -> Optional[dict]:
        if key in self._cache:
            ts, data = self._cache[key]
            if time.time() - ts < CACHE_TTL_SECONDS:
                return data
            del self._cache[key]
        return None

    def _set_cache(self, key: str, data: dict):
        self._cache[key] = (time.time(), data)

    def _check_rate_limit(self) -> bool:
        return time.time() < self._rate_limit_until

    def _handle_rate_limit(self, error: Exception, model: str = ""):
        """Block the specific model that hit a rate/availability limit."""
        error_str = str(error)
        target = model or self._active_model
        is_rate_limit = "429" in error_str or "quota" in error_str.lower()
        is_unavailable = "503" in error_str or "UNAVAILABLE" in error_str

        if is_rate_limit:
            is_daily = "PerDay" in error_str
            cooldown = 3600 if is_daily else 60
            self._blocked_models[target] = time.time() + cooldown
            print(f"[GeminiAdvisor] {target} blocked {cooldown}s ({'daily' if is_daily else 'per-min'} limit)")
        elif is_unavailable:
            self._blocked_models[target] = time.time() + 30
            print(f"[GeminiAdvisor] {target} temporarily unavailable, blocked 30s")

    def _pick_model(self) -> Optional[str]:
        """Pick the best available model, skipping blocked ones."""
        now = time.time()
        preferred = self._model_name
        if preferred not in self._blocked_models or now >= self._blocked_models[preferred]:
            self._blocked_models.pop(preferred, None)
            return preferred
        for model in FALLBACK_MODELS:
            if model not in self._blocked_models or now >= self._blocked_models[model]:
                self._blocked_models.pop(model, None)
                return model
        return None

    def _initialize(self):
        if not settings.gcp_project_id:
            self._init_error = "GCP Project ID not configured"
            return

        try:
            from google import genai
            self._client = genai.Client(
                vertexai=True, 
                project=settings.gcp_project_id, 
                location=settings.gcp_location
            )
            self._model_name = settings.gemini_model
            self._active_model = settings.gemini_model
            self._initialized = True
            print(f"[GeminiAdvisor] Initialized Vertex AI — primary: {settings.gemini_model}, fallbacks: {FALLBACK_MODELS}")
        except Exception as e:
            self._init_error = str(e)
            print(f"[GeminiAdvisor] Init error: {e}")

    @property
    def is_available(self) -> bool:
        return self._initialized and self._client is not None

    def _get_or_create_chat(self, session_id: str = "default"):
        if session_id not in self._chat_sessions:
            self._chat_sessions[session_id] = self._client.chats.create(
                model=self._model_name,
                config={"system_instruction": SYSTEM_PROMPT, **self._gen_config},
            )
        return self._chat_sessions[session_id]

    def clear_chat(self, session_id: str = "default"):
        self._chat_sessions.pop(session_id, None)

    # ── Core Chat ──

    async def chat(self, user_message: str, session_id: str = "default") -> dict:
        """Main conversational endpoint. Every call includes live sensor context."""
        if not self.is_available:
            return self._fallback_response(user_message)

        try:
            context = _build_sensor_context()

            recent_block = ""
            history_text = ""
            recent = list(self._conversation_history)[-6:]
            for entry in recent:
                role_tag = "User" if entry["role"] == "user" else "GreenMind"
                history_text += f"**{role_tag}**: {entry['text'][:200]}\n\n"

            enriched_prompt = (
                f"{context}\n\n---\n\n"
                f"{recent_block}"
                f"**User Question**: {user_message}\n\n"
                f"Respond as GreenMind. Use the live sensor data above to give specific, "
                f"data-driven advice. Reference actual values."
            )

            response = await self._generate_async(enriched_prompt)

            self._conversation_history.append({
                "role": "user", "text": user_message,
                "timestamp": get_now().isoformat(),
            })
            self._conversation_history.append({
                "role": "assistant", "text": response,
                "timestamp": get_now().isoformat(),
            })

            return {
                "answer": response,
                "model": self._active_model,
                "powered_by": "google_gemini",
            }
        except Exception as e:
            print(f"[GeminiAdvisor] Chat error: {e}")
            return self._fallback_response(user_message)

    # ── Creative Functions ──

    async def generate_daily_report(self) -> dict:
        """Generate a comprehensive daily greenhouse report."""
        if not self.is_available:
            return {"report": "Gemini API not available. Configure GEMINI_API_KEY.", "powered_by": "fallback"}

        context = _build_sensor_context()

        # Gather 24h stats for key sensors
        stats_lines = ["## 24-Hour Statistics Summary"]
        for zone, sensor in [
            ("zone_air", "humidity"),
            ("zone_bed_a", "soil_temperature"), ("zone_bed_a", "soil_ph"), ("zone_bed_a", "soil_moisture"),
            ("zone_bed_b", "soil_temperature"), ("zone_bed_b", "soil_ph"), ("zone_bed_b", "soil_moisture"),
            ("zone_bed_c", "soil_temperature"), ("zone_bed_c", "soil_ph"), ("zone_bed_c", "soil_moisture"),
        ]:
            stats_lines.append(f"- {zone}/{sensor}: {_build_history_context(zone, sensor, 200)}")

        prompt = (
            f"{context}\n\n{chr(10).join(stats_lines)}\n\n---\n\n"
            f"Generate a comprehensive **Daily Greenhouse Report** with these sections:\n"
            f"1. **Executive Summary** (2-3 sentences, overall health grade A-F)\n"
            f"2. **Climate Analysis** (temperature, humidity, VPD, light trends)\n"
            f"3. **Water & Nutrition** (irrigation status, pH/EC, reservoir)\n"
            f"4. **Issues & Risks** (any problems detected, disease risk assessment)\n"
            f"5. **Recommendations** (top 3-5 prioritized actions)\n"
            f"6. **Tomorrow's Plan** (what to watch for, scheduled tasks)\n\n"
            f"Use real data. Be specific with numbers. Format with markdown."
        )

        try:
            response = await self._generate_async(prompt)
            return {"report": response, "powered_by": "google_gemini", "generated_at": get_now().isoformat()}
        except Exception as e:
            return {"report": f"Error generating report: {e}", "powered_by": "error"}

    async def generate_grow_plan(self, crop_name: str, duration_weeks: int = 4) -> dict:
        """Generate a week-by-week growing plan for a specific crop."""
        if not self.is_available:
            return {"plan": "Gemini API not available.", "powered_by": "fallback"}

        context = _build_sensor_context()
        crop = CROP_PROFILES.get(crop_name.lower(), CROP_PROFILES["general"])

        prompt = (
            f"{context}\n\n---\n\n"
            f"Create a detailed **{duration_weeks}-Week Growing Plan for {crop.name}** in this greenhouse.\n\n"
            f"Crop requirements:\n"
            f"- Temperature: {crop.temp_min}-{crop.temp_max}°C (ideal: {crop.temp_ideal}°C)\n"
            f"- Humidity: {crop.rh_min}-{crop.rh_max}%\n"
            f"- pH: {crop.ph_min}-{crop.ph_max}\n"
            f"- EC: {crop.ec_min}-{crop.ec_max} mS/cm\n"
            f"- Light: {crop.light_hours}h, DLI: {crop.light_dli} mol/m²/day\n"
            f"- Notes: {crop.notes}\n\n"
            f"For each week include:\n"
            f"- **Target conditions** (specific setpoints for T, RH, pH, EC)\n"
            f"- **Key tasks** (seeding, transplanting, pruning, training)\n"
            f"- **Nutrient schedule** (EC targets, any supplements)\n"
            f"- **Watch points** (common problems at this stage)\n\n"
            f"Consider the CURRENT conditions shown above and note any adjustments needed. "
            f"Format with markdown. Be practical and specific."
        )

        try:
            response = await self._generate_async(prompt)
            return {"plan": response, "crop": crop.name, "weeks": duration_weeks, "powered_by": "google_gemini"}
        except Exception as e:
            return {"plan": f"Error: {e}", "powered_by": "error"}

    async def what_if_scenario(self, scenario: str) -> dict:
        """Simulate a what-if scenario using Gemini's reasoning."""
        if not self.is_available:
            return {"analysis": "Gemini API not available.", "powered_by": "fallback"}

        context = _build_sensor_context()
        prompt = (
            f"{context}\n\n---\n\n"
            f"**What-If Scenario Analysis**\n\n"
            f"The user wants to know: \"{scenario}\"\n\n"
            f"Analyze this scenario step by step:\n"
            f"1. **Current State**: Summarize relevant current conditions\n"
            f"2. **Predicted Effects**: What would change and in what order?\n"
            f"3. **Timeline**: How quickly would effects be visible?\n"
            f"4. **Risks**: What could go wrong?\n"
            f"5. **Recommendation**: Should they do it? What precautions?\n\n"
            f"Use physics and plant science. Reference actual sensor values. Be specific."
        )

        try:
            response = await self._generate_async(prompt)
            return {"analysis": response, "scenario": scenario, "powered_by": "google_gemini"}
        except Exception as e:
            return {"analysis": f"Error: {e}", "powered_by": "error"}

    async def diagnose_plant_image(self, image_bytes: bytes, description: str = "") -> dict:
        """Use Gemini Vision to diagnose plant health from an image."""
        if not self.is_available:
            return {"diagnosis": "Gemini API not available.", "powered_by": "fallback"}

        try:
            from google.genai import types
            import asyncio

            context = _build_sensor_context()

            prompt = (
                f"You are GreenMind, an expert plant pathologist analyzing a greenhouse plant image.\n\n"
                f"{context}\n\n---\n\n"
                f"{'User notes: ' + description + chr(10) + chr(10) if description else ''}"
                f"Analyze this plant image and provide:\n"
                f"1. **Plant Identification** (species if identifiable)\n"
                f"2. **Health Assessment** (healthy / mild stress / moderate stress / severe / critical)\n"
                f"3. **Visible Symptoms** (leaf color, spots, wilting, pests, etc.)\n"
                f"4. **Likely Diagnosis** (nutrient deficiency, disease, pest, environmental stress)\n"
                f"5. **Connection to Sensor Data** (do current greenhouse conditions explain the symptoms?)\n"
                f"6. **Treatment Plan** (specific steps to fix the problem)\n\n"
                f"Be specific and reference actual sensor data when relevant."
            )

            image_part = types.Part.from_bytes(data=image_bytes, mime_type="image/jpeg")

            model = self._pick_model() or self._model_name
            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(
                None,
                lambda: self._client.models.generate_content(
                    model=model,
                    contents=[prompt, image_part],
                ),
            )
            return {"diagnosis": response.text, "powered_by": "google_gemini_vision"}
        except Exception as e:
            self._handle_rate_limit(e, self._active_model)
            return {"diagnosis": f"Error analyzing image: {e}", "powered_by": "error"}

    async def explain_anomaly(self, sensor_id: str, sensor_type: str, zone_id: str, value: float) -> dict:
        """Ask Gemini to explain an anomaly in plain language."""
        if not self.is_available:
            return {"explanation": "Gemini not available.", "powered_by": "fallback"}

        context = _build_sensor_context()
        history_text = _build_history_context(zone_id, sensor_type, 50)

        prompt = (
            f"{context}\n\n---\n\n"
            f"**Anomaly Detected!**\n"
            f"- Sensor: {sensor_id} ({sensor_type}) in {zone_id}\n"
            f"- Anomalous value: {value}\n"
            f"- History: {history_text}\n\n"
            f"Explain in plain language:\n"
            f"1. **What happened?** (describe the anomaly simply)\n"
            f"2. **Why might this have happened?** (most likely causes)\n"
            f"3. **Is this a sensor fault or a real event?** (how to tell)\n"
            f"4. **What should the user do?** (immediate action + monitoring)\n"
            f"5. **Impact on crops** (what this means for plant health)\n"
        )

        try:
            response = await self._generate_async(prompt)
            return {"explanation": response, "sensor_id": sensor_id, "powered_by": "google_gemini"}
        except Exception as e:
            return {"explanation": f"Error: {e}", "powered_by": "error"}

    async def suggest_automation_schedule(self) -> dict:
        """Generate a smart 24-hour automation schedule based on current data."""
        if not self.is_available:
            return {"schedule": "Gemini not available.", "powered_by": "fallback"}

        context = _build_sensor_context()
        prompt = (
            f"{context}\n\n---\n\n"
            f"Design an optimal **24-hour automation schedule** for this greenhouse.\n\n"
            f"For each time block (early morning, morning, midday, afternoon, evening, night), specify:\n"
            f"- **Actuator states** (which fans/pumps/heater/lights should be on/off)\n"
            f"- **Setpoints** (target temperature, humidity ranges)\n"
            f"- **Irrigation windows** (when and how long)\n"
            f"- **Reasoning** (why this schedule optimizes for the active crop)\n\n"
            f"Consider energy efficiency, day/night cycles, and plant biology. "
            f"Present as a clear table or timeline. Reference current conditions to justify changes."
        )

        try:
            response = await self._generate_async(prompt)
            return {"schedule": response, "powered_by": "google_gemini"}
        except Exception as e:
            return {"schedule": f"Error: {e}", "powered_by": "error"}

    async def educational_explain(self, topic: str) -> dict:
        """Explain a greenhouse/hydroponics concept in beginner-friendly terms."""
        if not self.is_available:
            return {"explanation": "Gemini not available.", "powered_by": "fallback"}

        context = _build_sensor_context()
        prompt = (
            f"{context}\n\n---\n\n"
            f"The user wants to learn about: **{topic}**\n\n"
            f"Explain this in a beginner-friendly way:\n"
            f"1. **What is it?** (simple definition)\n"
            f"2. **Why does it matter?** (impact on plants)\n"
            f"3. **How does it work in THIS greenhouse?** (reference real sensor values)\n"
            f"4. **Practical tips** (what should a beginner watch for)\n"
            f"5. **Fun fact** (something interesting about this topic)\n\n"
            f"Use analogies and simple language. Make it engaging."
        )

        try:
            response = await self._generate_async(prompt)
            return {"explanation": response, "topic": topic, "powered_by": "google_gemini"}
        except Exception as e:
            return {"explanation": f"Error: {e}", "powered_by": "error"}

    # ── Analytics Functions (replacing local-only endpoints) ──

    async def generate_insights(self) -> dict:
        """Generate Gemini-powered insights using structured JSON output."""
        if not self.is_available:
            return None

        cached = self._get_cached("insights")
        if cached:
            return cached

        context = _build_sensor_context()
        prompt = (
            f"{context}\n\n---\n\n"
            f"Analyze the greenhouse data above and generate a JSON array of insights. "
            f"Each insight must have these fields:\n"
            f'- "title": short title (5-10 words)\n'
            f'- "message": detailed explanation with actual sensor values (1-2 sentences)\n'
            f'- "priority": one of "critical", "high", "medium", "low", "info"\n'
            f'- "category": one of "climate", "vpd", "irrigation", "hydroponics", "reservoir", "efficiency"\n'
            f'- "action": specific recommended action, or null if info-only\n'
            f'- "icon": one of "thermometer", "droplets", "wind", "gauge", "beaker", "sun", "waves", "zap", "check"\n\n'
            f"Return 4-8 insights, sorted by priority (critical first). "
            f"Always include VPD analysis. Include efficiency tips if actuators are misconfigured. "
            f"Output ONLY valid JSON array."
        )

        try:
            response = await self._generate_async(prompt, {
                "response_mime_type": "application/json",
            })
            text = response.strip()
            insights = json.loads(text)
            if isinstance(insights, dict) and "insights" in insights:
                insights = insights["insights"]
            if not isinstance(insights, list):
                insights = [insights] if isinstance(insights, dict) else []
            result = {"insights": insights, "powered_by": "google_gemini"}
            self._set_cache("insights", result)
            return result
        except json.JSONDecodeError:
            return None
        except Exception as e:
            print(f"[GeminiAdvisor] Insights error: {e}")
            return None

    async def generate_summary(self) -> dict:
        """Generate a Gemini-powered natural language summary."""
        if not self.is_available:
            return None

        cached = self._get_cached("summary")
        if cached:
            return cached

        context = _build_sensor_context()
        prompt = (
            f"{context}\n\n---\n\n"
            f"Write a concise 2-3 sentence summary of the greenhouse's current status. "
            f"Mention the most important readings (temperature, humidity, VPD, soil moisture, pH). "
            f"State whether conditions are good or if action is needed. "
            f"Use actual numbers from the data. Keep it natural and helpful."
        )

        try:
            response = await self._generate_async(prompt)
            result = {"summary": response.strip(), "powered_by": "google_gemini"}
            self._set_cache("summary", result)
            return result
        except Exception as e:
            print(f"[GeminiAdvisor] Summary error: {e}")
            return None

    async def analyze_forecast(self, zone_id: str, sensor_type: str,
                                forecast_points: list, historical_stats: dict) -> dict:
        """Have Gemini interpret forecast data and provide actionable analysis."""
        if not self.is_available:
            return None

        cache_key = f"forecast:{zone_id}:{sensor_type}"
        cached = self._get_cached(cache_key)
        if cached:
            return cached

        context = _build_sensor_context()
        forecast_text = "\n".join([
            f"  - {p['timestamp']}: predicted={p['predicted_value']}, "
            f"range=[{p['lower_bound']}, {p['upper_bound']}]"
            for p in forecast_points[:12]
        ])

        prompt = (
            f"{context}\n\n---\n\n"
            f"**Forecast Analysis Request**\n\n"
            f"Sensor: {sensor_type} in {zone_id}\n"
            f"Historical stats: {json.dumps(historical_stats)}\n\n"
            f"Forecast points (next hour):\n{forecast_text}\n\n"
            f"Provide a brief analysis:\n"
            f"1. **Trend**: Is the value rising, falling, or stable?\n"
            f"2. **Risk Assessment**: Will it go out of ideal range? When?\n"
            f"3. **Recommended Action**: What should the user do now to prepare?\n"
            f"4. **Confidence Note**: How reliable is this forecast given the data?\n\n"
            f"Keep it concise (3-5 sentences). Reference actual numbers."
        )

        try:
            response = await self._generate_async(prompt)
            result = {"analysis": response.strip(), "powered_by": "google_gemini"}
            self._set_cache(cache_key, result)
            return result
        except Exception as e:
            print(f"[GeminiAdvisor] Forecast analysis error: {e}")
            return None

    async def analyze_all_anomalies(self, anomaly_data: list) -> dict:
        """Have Gemini analyze all sensor anomalies and provide a unified report."""
        if not self.is_available:
            return None

        cached = self._get_cached("anomalies")
        if cached:
            return cached

        context = _build_sensor_context()
        anomaly_text = json.dumps(anomaly_data, indent=2, default=str)

        prompt = (
            f"{context}\n\n---\n\n"
            f"**Anomaly Detection Results**\n\n"
            f"```json\n{anomaly_text}\n```\n\n"
            f"Analyze ALL the sensor anomaly results above and provide:\n"
            f"1. **Overall Health**: Are there any real anomalies? Rate the system health.\n"
            f"2. **Flagged Sensors**: For each anomaly detected (is_anomaly=true), explain what happened and likely cause.\n"
            f"3. **Cross-Sensor Correlation**: Do any anomalies relate to each other?\n"
            f"4. **Action Items**: What should the user do about each anomaly?\n"
            f"5. **Sensor Reliability**: Any signs of sensor drift or fault?\n\n"
            f"Be specific with sensor IDs and values. Keep it practical."
        )

        try:
            response = await self._generate_async(prompt)
            result = {"analysis": response.strip(), "powered_by": "google_gemini"}
            self._set_cache("anomalies", result)
            return result
        except Exception as e:
            print(f"[GeminiAdvisor] Anomaly analysis error: {e}")
            return None

    async def interpret_statistics(self, zone_id: str, sensor_type: str,
                                    stats: dict) -> dict:
        """Have Gemini interpret statistics in context of the greenhouse."""
        if not self.is_available:
            return None

        cache_key = f"stats:{zone_id}:{sensor_type}"
        cached = self._get_cached(cache_key)
        if cached:
            return cached

        context = _build_sensor_context()
        prompt = (
            f"{context}\n\n---\n\n"
            f"**Statistics for {sensor_type} in {zone_id}:**\n"
            f"- Count: {stats.get('count')} readings\n"
            f"- Mean: {stats.get('mean')}, Std: {stats.get('std')}\n"
            f"- Min: {stats.get('min')}, Max: {stats.get('max')}\n"
            f"- Median: {stats.get('median')}, Latest: {stats.get('latest')}\n"
            f"- Trend: {stats.get('trend')}\n\n"
            f"Interpret these statistics for the user:\n"
            f"1. Is the variability (std) normal or concerning?\n"
            f"2. Is the current value (latest) typical or unusual?\n"
            f"3. What does the trend mean for the crop?\n"
            f"4. Any recommendations based on these patterns?\n\n"
            f"Keep it brief (3-4 sentences). Use plain language."
        )

        try:
            response = await self._generate_async(prompt)
            result = {"interpretation": response.strip(), "powered_by": "google_gemini"}
            self._set_cache(cache_key, result)
            return result
        except Exception as e:
            print(f"[GeminiAdvisor] Stats interpretation error: {e}")
            return None

    # ── Async Helpers with Automatic Model Fallback ──

    def _is_retriable(self, error: Exception) -> bool:
        s = str(error)
        return "429" in s or "503" in s or "UNAVAILABLE" in s or "quota" in s.lower()

    async def _send_async(self, chat, message: str) -> str:
        """Send a message to a Gemini chat session."""
        import asyncio
        loop = asyncio.get_event_loop()
        response = await loop.run_in_executor(
            None, lambda: chat.send_message(message)
        )
        return response.text

    async def _generate_async(self, prompt: str, config_override: dict = None) -> str:
        """Generate content, automatically trying fallback models on failure."""
        import asyncio

        base_config = {"system_instruction": SYSTEM_PROMPT, "temperature": 0.7, "top_p": 0.9, "max_output_tokens": 2048}
        if config_override:
            base_config.update(config_override)

        models_tried = set()
        last_error = None
        max_attempts = len(FALLBACK_MODELS) + 1

        for _ in range(max_attempts):
            model = self._pick_model()
            if model is None or model in models_tried:
                break
            models_tried.add(model)
            try:
                loop = asyncio.get_event_loop()
                current_model = model
                response = await loop.run_in_executor(
                    None,
                    lambda m=current_model, cfg=base_config.copy(): self._client.models.generate_content(
                        model=m, contents=prompt, config=cfg,
                    ),
                )
                if current_model != self._model_name:
                    print(f"[GeminiAdvisor] Succeeded with fallback model: {current_model}")
                self._active_model = current_model
                return response.text
            except Exception as e:
                last_error = e
                self._handle_rate_limit(e, model)
                if self._is_retriable(e):
                    print(f"[GeminiAdvisor] {model} failed, trying next fallback...")
                    continue
                raise

        if last_error:
            raise last_error
        raise RuntimeError("All Gemini models are rate-limited. Please wait a few minutes.")

    # ── Fallback ──

    def _fallback_response(self, user_message: str) -> dict:
        """Use the rule-based advisor as fallback when Gemini is not available."""
        result = rule_advisor.answer_question(user_message)
        fallback_note = ""
        if self._init_error:
            fallback_note = (
                f"\n\n---\n*Note: AI is running in local mode. "
                f"To enable Google Gemini, set your `GEMINI_API_KEY` in the `.env` file. "
                f"Get a free key at [Google AI Studio](https://aistudio.google.com/apikey). "
                f"Error: {self._init_error}*"
            )
        return {
            "answer": result.answer + fallback_note,
            "model": "rule-based (fallback)",
            "powered_by": "local_rules",
            "insights": [
                {
                    "title": i.title, "message": i.message,
                    "priority": i.priority.value, "category": i.category,
                    "action": i.action, "icon": i.icon,
                }
                for i in result.insights
            ],
        }


gemini_advisor = GeminiAdvisor()
